---
title: "Shared Cleaning"
output: html_notebook
---

### Read in Layers from GDB
```{r}
library(sf)

gdb <- "/Users/ryankobler/Desktop/thesis/data/Reed/data.gdb"

layers <- st_layers(gdb)

constraints <- st_read(gdb, layer = "bli_development_capacity")
gisimpcop <- st_read(gdb, layer = "CoP_GISImprovement")
impsegcop <- st_read(gdb, layer = "CoP_OrionImprovementSegment")
gispropcop <- st_read(gdb, layer = "CoP_GISProperty")
allpropcop <- st_read(gdb, layer = "CoP_AllProperties")
segchar <- st_read(gdb, layer = "Seg_Char")
rollhist <- st_read(gdb, layer = "roll_history")
rollvals <- st_read(gdb, layer = "roll_values")
impseg <- st_read(gdb, layer = "imp_segments")
salescop <- st_read(gdb, layer = "CoP_OrionSalesHistory")
school <- st_read(gdb, layer = "school_attendance_areas")
imp <- st_read(gdb, layer = "improvements")

firelu <- st_read(gdb, layer = "Fireplace_Lookup")
segmentlu <- st_read(gdb, layer = "Segment_Type_Lookup")
imptypelu <- st_read(gdb, layer = "Imp_Type_Lookup")
impcodeslu <- st_read(gdb, layer = "Improvement_Codes_Lookup") 
propcodelu <- st_read(gdb, layer = "Property_Code_Lookup") 
plumblu <- st_read(gdb, layer = "Plumbing_Lookup")

```

### Function to trim data set
Trim to 2014 to 2018 (December 1 for each year). The function assumes that the `SaleDate` column of the salescop df has been changed to a Date object. 

```{r}
salescop$SaleDate <- as.Date(salescop$SaleDate)

year <- 2018
endDate <- as.Date(paste0(year,"-12-01"))
beginDate <- as.Date(paste0(year - 4, "-12-01"))

# Adds December 1 to the end of each year. 
trim <- function(begin, end){
  salescop %>% filter(SaleDate > begin & SaleDate < end)
}

trimmed <- trim(beginDate, endDate)
```


### Which dfs need to be reshaped?
impsegcop

```{r}
library(reshape2)
for(layer in datanames){
  l <- get(layer)
  manytoOne<- sum(data.frame(table(l$PropID))$Freq > 1)
  print(paste(layer, manytoOne, sep = ": "))
}


impseg$PropertyID 
head(impseg)
melt(impseg, idvars = c("PropertyID", "Segment_Num"))
colnames(impseg)
impseg$Segment_Num

names <- colnames(impseg)
drop <- c("Segment_Num","Structure_Num","Seg_Type", "SegID", "PropertyID")
keep <- names[!names %in% drop]


library(dplyr)
library(tidyr)
impseg %>%
  gather(Var, val, starts_with("value")) %>% 
  unite(Var1,Var, y) %>% 
  spread(Var1, val)

library(data.table)
subimpseg <- impseg[1:100,]

# 
salma <- dcast(setDT(subimpseg), PropertyID~Segment_Num, value.var=c(keep))

```






