---
title: "Cleaning joined data"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages
```{r}
library(tidyverse)
library(here)
library(magrittr)
```

# Import joined thesis data
```{r}
df <- read.csv(here("DATA", "altered", "thesis-data_4-25.csv"))

constraints <- c("conAirHgt",
                    "conCovrly", "conPovrly",
                   "conHist", "conHistLdm", 
                 "conLSHA", "conLUST",
                   "conNoise", "conSewer", "conSLIDO",
                   "conSlp25", "conStorm", "conTranCap", "conTranSub",
                   "conTranInt", "conTranSub", "conWater", 
                  "conPubOwn", "conFld100")
# define helper function to switch NAs in the constraints to 0s
to0 <- function(x){ifelse(is.na(x), 0, x)}

pullVarname <- function(vars){
  sapply(vars, gsub, pattern = "\\(|\\)|I\\(|log|\\^2", replace = "") %>%
    unique()
}

# CREATE FLAG & ARMS LENGTH VARIABLES
df %<>%
  mutate(n_fireplaces = ifelse(is.na(n_fireplaces), 0, n_fireplaces), 
         saledate = as.Date(saledate),
         lnprice = log(SALEPRICE),
         # define flags
         proud_flag =  grepl("PROUD", OWNER1) | 
           grepl("PROUD", OWNER2) | grepl("PROUD", OWNER3),
         trust_flag = grepl("TRUST", OWNER1) | 
           grepl("TRUST", OWNER2) | grepl("TRUST", OWNER3), 
         top_1 =  SALEPRICE > quantile(SALEPRICE, .99),
         vacant_dummy = PRPCD_DESC == "VACANT LAND",
         price_diff = SALEPRICE - LANDVAL3, 
         price_ratio = SALEPRICE/LANDVAL3 * 100,         
         #make percentages
         pct_canopy_cov = 100*pct_canopy_cov,
         percent_vacant = 100*percent_vacant)

#export to csv
#write.csv(df, here("DATA", "altered", "thesis-data_4-25.csv"))
```


# Drops 
• `df`: 34,628 observations

• `trim`: 31,388

```{r}
df <- read.csv(here("DATA", "altered", "thesis-data_4-25.csv"))

# MAKE DROPS
trim <- df %>% 
  filter(proud_flag == F, top_1 == F,
           price_ratio > 100, vacant_dummy == F) %>%
  mutate(YEARBUILT = as.numeric(YEARBUILT)) %>%
  mutate(YEARBUILT = case_when(
    YEARBUILT < 1000 ~ NA_real_,
    YEARBUILT > 2019 ~ NA_real_,
    TRUE ~ YEARBUILT))

constraint_sums <- trim %>%
  dplyr::select(constraints) %>%
  rowSums()

trim %<>%
  mutate(is_constrained = constraint_sums > 0)

# ---------------
# SQUARE FOOTAGE VARIABLES
# garage sqft
gar_sqft_sum <- trim %>%
  dplyr::select(matches("gar")) %>%
  rowSums()

# attic sqft
attic_sqft_sum <- trim %>%
  dplyr::select(matches("attic")) %>%
  rowSums()

# basement sqft
bsmt_sqft_sum <- trim %>%
  dplyr::select(matches("bsmt")) %>%
  dplyr::select(-c("BSMT.PARKING","BSMT.GAR")) %>%
  rowSums()

# define dummies
trim %<>%
  mutate(garage_sqft = gar_sqft_sum,
         garage_dum = garage_sqft > 0,
         attic_sqft = attic_sqft_sum,
         attic_dum = attic_sqft > 0,
         bsmt_sqft = bsmt_sqft_sum,
         bsmt_dum = bsmt_sqft > 0,
         year_sold = format(as.Date(saledate), "%Y"))
```

# Clean SFR
(drop based on number of units, full baths, BLDGSQFT, and taxlot area)
• `sfr.dat`: 24,715

(drop missing variables used for regression, missing at random?)
• `sfr.dat.cleaned`: 22,438

```{r}
sfr_vars <- c("dist_cityhall", "dist_ugb", "h_baths",
              "f_baths", "AREA", "maxheight", "totalsqft", "garage_dum","bsmt_dum",
              "pct_canopy_cov", "YEARBUILT", "n_fireplaces", "CN_score", "attic_dum", "year_sold", 
              "percent_vacant", "I(AREA^2)", "I(totalsqft^2)", "I(CN_score^2)")

sfr.dat <- trim %>%
  filter(prop_type == "Single-family") %>%
  mutate(empty_lot_flag = BLDGSQFT == 0, is.na(totalsqft),
         maybe_mfr_flag = UNITS > 5 | f_baths > 10,
         big_sqft_flag = BLDGSQFT > 10000,
         big_bsmt_flag = bsmt_sqft > 9000,
         big_area_flag = AREA > 100000) %>%
    filter(!empty_lot_flag,
         !maybe_mfr_flag, 
         !big_area_flag,
         !big_sqft_flag)

sfr.dat.cleaned <- sfr.dat %>%
  select(pullVarname(sfr_vars), constraints, STATE_ID, 
         BLDGSQFT, lnprice, nbhd, sextant) %>%
  drop_na()

#write.csv(sfr.dat.cleaned, here("DATA", "altered", "sfr-cleaned.csv"))
```

# Clean MFR
• `mfr.dat`: 4,187
(drop missing variables used for regression, missing at random?)

• `mfr.dat.cleaned`: 
```{r}
mfr_vars <- c("dist_cityhall", "dist_ugb", "h_baths",
              "f_baths", "AREA", "maxheight", "garage_dum","bsmt_dum", 
              "pct_canopy_cov", "YEARBUILT", "CN_score", "attic_dum", "year_sold", "n_fireplaces",
              "percent_vacant", "n_units", "n_buildings", "totalsqft", "I(totalsqft^2)", "I(AREA^2)", "I(f_baths^2)")


mfr.dat <- trim %>%
  filter(prop_type == "Multi-family",
         !(is.na(totalsqft) & BLDGSQFT == 0),
         AREA < 100000) %>%
  mutate(bldgsqft_imp = case_when(is.na(totalsqft) ~ BLDGSQFT,
                                  BLDGSQFT == 0 ~ totalsqft,
                                  TRUE ~ BLDGSQFT),
         imputed = is.na(totalsqft)) %>%
  filter(bldgsqft_imp < 60000)

mfr.dat.cleaned <- mfr.dat %>%
  select(pullVarname(mfr_vars), constraints, STATE_ID, 
         BLDGSQFT, lnprice, nbhd, sextant) %>%
  drop_na()

# write.csv(mfr.dat, here("DATA", "altered", "mfr-cleaned.csv"))

```




