---
title: "clean_2-25"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# CLEANING EVERYTHING
```{r}
library(tidyverse)
library(readxl)
library(magrittr)
library(stringr)

df <- read_csv("./DATA/thesis-data.csv")
```

# SUMMARY STATS
```{R}
summary(df$percent_vacant)
summary(df$SALEPRICE)
table(df$prop_type)
```

# GENERATE YEAR VARIABLE
```{r}

```

# BUYERS AND SELLERS
```{r}


```

# DROPS
```{R}

df %<>%
  mutate(proud_flag =  grepl("PROUD", OWNER1) | grepl("PROUD", OWNER2) | grepl("PROUD", OWNER3),
         trust_flag = grepl("TRUST", OWNER1) | grepl("TRUST", OWNER2) | grepl("TRUST", OWNER3), 
         top_1 =  SALEPRICE > quantile(SALEPRICE, .99),
         price_diff = SALEPRICE - LANDVAL3, 
         price_ratio = SALEPRICE/LANDVAL3 * 100,
         vacant_dummy = PRPCD_DESC == "VACANT LAND") %>%
  mutate(arms_length = price_ratio > 20)

constraints <- c("conWetland", "conNatAm", 
                   "conAirHgt", "conCovrly", "conPovrly", "conHeliprt",
                   "conHist", "conHistLdm", "conInstit", "conLSHA", "conLUST",
                   "conNoise", "conPrvCom", "conSewer", "conSLIDO",
                   "conSlp25", "conStorm", "conTranCap", "conTranSub",
                   "conTranInt", "conTranSub", "conView", "conWater", 
                 "conGW", "conPubOwn", "conFldway", "conFld100", "conECSI")



# switch the NAs in the constraints to 0s
to0 <- function(x){ifelse(is.na(x), 0, x)}

#copy <- df
#copy[constraints][is.na(copy[constraints])] <- 0

trim <- df %>% 
  filter(proud_flag == F & top_1 == F & arms_length == T & vacant_dummy == F) %>%
  mutate_at(vars(constraints), to0) 

constraint_sums <- trim %>%
  select(constraints) %>%
  rowSums()

trim %<>%
  mutate(is_constrained = constraint_sums > 0)
```


```{r}
# first regression
m1 <- lm(data = trim %>% filter(prop_type == "Single-family"), I(log(SALEPRICE)) ~ is_constrained + f_baths + h_baths +
           n_fireplaces + YEARBUILT + BLDGSQFT + AREA + dist_ugb + dist_cityhall + `BUILT-IN GARAGE` + CN_score + HIGH_SCH + ADUdummy + NAME)
summary(m1)
m1_mfr <- lm(data = trim %>% filter(prop_type == "Multi-family"), I(log(SALEPRICE)) ~ is_constrained + f_baths + h_baths +
           n_fireplaces + YEARBUILT + BLDGSQFT + AREA + dist_ugb + dist_cityhall +
           `BUILT-IN GARAGE` + CN_score + HIGH_SCH + ADUdummy + NAME)
summary(m1)
summary(m1_mfr)

# separating out the constraints
cons_form <- paste(constraints, collapse = " + ")
formula <- as.formula(paste0("I(log(SALEPRICE)) ~ ", const_form))
m2 <- lm(data = trim %>% filter(prop_type == "Single-family"), formula)
summary(m2)

# model from pre analysis
vars <- c("CN_score", "YEARBUILT", "dist_ugb", "dist_cityhall", "AREA", "BLDGSQFT", "f_baths", "h_baths", "n_fireplaces", "ADUdummy", "pct_canopy_cov", "sale_zone", "`BSMT FINISHED`")

col_vars <- paste(vars, collapse = " + ")
full_vars <- paste(c(col_vars, cons_form), collapse = " + ")
y <- "I(log(SALEPRICE)) ~ "
formula <- as.formula(paste0(y, full_vars))

m3 <- lm(data = trim %>% filter(prop_type == "Single-family"), formula)
summary(m3)
```

What can the values be interpreted as?






