---
title: "MU_final"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Import Packages + Read in Data

```{r, include = TRUE}
library(tidyverse)
library(magrittr)
library(here)
library(data.table)
library(MASS)
library(knitr)
library(stargazer)
library(lubridate)
library(mapview)
library(sf)

# read in csv
thesis_data <- read_csv(here::here("DATA","thesis-data.csv"))
```

# Wrangling

```{r, echo = TRUE}
# Split Data
MU <- thesis_data %>%
  filter(prop_type == "Mixed Use")

#-------------------------------------------------------------------------

# Make a string of constraints and percent canopy names called "con_names"
clean <- SFR %>%
  dplyr::select(contains("con"), contains("pct")) %>%
  dplyr::select(-c("CONCRETE", "FIN SECOND", "PAVING/CONCRETE ONLY", "UNF SECOND", "conFldway", "pct_conFldway", "pct_canopy_cov")) 
clean_names <- names(clean)
con_names <- paste(clean_names, collapse = " + ")

# switch the NAs in the constraints to 0s
to0 <- function(x){ifelse(is.na(x), 0, x)}

#-------------------------------------------------------------------------

# Format SFR Dataframe: 
# Select variables, mutate filtering parameters. No actual filtering done at this point, all SFR vars kept. 
testmu1 <- MU %>%
  dplyr::select(-c(OWNER2, OWNER3, OWNERZIP, 
            MKTVALYR1, MKTVALYR2,
            BLDGVAL1, BLDGVAL2,
            LANDVAL1, LANDVAL2,  
            TOTALVAL1, TOTALVAL2,
            MS_GRADE, ES_GRADE,
            LEGAL_DESC, 
            LANDUSE, 
            BEDROOMS, ACC_STATUS, 
            NAME, COMMPLAN, SHARED, 
            COALIT, HORZ_VERT, AUDIT_NBRH, 
            MIDDLE_SCH,  Category, SOURCE, 
            FRONTAGE, COUNTY, YEARBUILT, bldgtype)) %>%
  mutate(top_1 =  SALEPRICE > quantile(SALEPRICE, .99),
         MKTVALYR3 = case_when(MKTVALYR3 != 2018 ~ 2017, 
                                         TRUE ~ 2018),
         price_diff = SALEPRICE - LANDVAL3, 
         price_ratio = SALEPRICE/LANDVAL3 * 100,
         vacant_dummy = as.numeric(PRPCD_DESC == "VACANT LAND"))

#-------------------------------------------------------------------------

#garage sqft
gar_sqft_sum <- testmu1 %>%
  dplyr::select(matches("gar"), matches("car")) %>%
  rowSums()

# basement sqft
bsmt_sqft_sum <- testmu1 %>%
  dplyr::select(matches("bsmt")) %>%
  dplyr::select(-c("BSMT PARKING","BSMT GAR")) %>%
  rowSums()

# creating zone change dummy
zone_test <- testmu1 %>%
  dplyr::select(matches("zone"), -c(ZONE_DESC_aug2016, ZONE_DESC_aug2018, ZONE_DESC_feb2018, `Zone Description`, sale_zone)) %>%
  mutate_all(str_replace, pattern = "R", replacement = "") %>%
  mutate_all(funs(as.numeric)) %>%
  rowSums()

testmu1 %<>%
  mutate(garage_sqft = gar_sqft_sum,
         garage_dum = as.numeric(garage_sqft > 0),
         bsmt_sqft = bsmt_sqft_sum,
         bsmt_dum = as.numeric(bsmt_sqft > 0),
         n_fireplaces = replace_na(n_fireplaces, 0),
         fireplace_dum = as.numeric(n_fireplaces > 0),
         ADUdummy = as.numeric(ADUdummy > 0),
         total_canopy_cov = replace_na(total_canopy_cov, 0),
         canopy_dum = as.numeric(total_canopy_cov > 0),
         sum_z = zone_test,
         avg_z = sum_z/9,
         z_change = case_when(avg_z == 5 ~ 0,
                                      TRUE ~ 1),
         totalsqft_sqd = totalsqft*totalsqft,
         taxlot_area_sqd = taxlot_area*taxlot_area)

#-------------------------------------------------------------------------

# Clean SFR dataframe: 
# remove based on filtering parameters, set NAs as zero, add in improvements
testmu2 <- testmu1 %>%
  dplyr::select(-c(matches("zone"))) %>%
  mutate_at(vars(clean_names), to0) %>%
  mutate(arms_length = price_ratio > 20,
         yearbuilt = na_if(yearbuilt, 0),
         saledate = mdy(saledate), 
         year_sold = year(saledate),
         age_sold = year_sold - yearbuilt,
         percent_vacant = percent_vacant*100,
         SALEPRICElog = log(SALEPRICE)) %>%
  filter(yearbuilt > 1500,
         totalsqft != 0,
         age_sold >= 0, 
         top_1 == FALSE, 
         arms_length == TRUE, 
         vacant_dummy == FALSE) 

#-------------------------------------------------------------------------

# Select final relevant variables
mu_dat1 <- testmu2 %>%
  dplyr::select(
    STATE_ID, RNO, PROPERTYID, TLID, 
    OWNER1, SITEADDR, SITEZIP, TAXCODE, PRPCD_DESC, 
    MKTVALYR3, LANDVAL3, BLDGVAL3, TOTALVAL3, 
    saledate, SALEPRICE, SALEPRICElog, age_sold,
    totalsqft, totalsqft_sqd, taxlot_area, taxlot_area_sqd, 
    volume, FLOORS, UNITS, 
    f_baths, h_baths, n_fireplaces, fireplace_dum, ADUdummy, 
    garage_sqft, garage_dum, bsmt_sqft, bsmt_dum, 
    percent_vacant, vacant_dummy,
    pct_canopy_cov, total_canopy_cov, canopy_dum, zone_change = z_change,
    CN_score, Neighborhood = MapLabel, HIGH_SCH, ELEM_SCH, dist_cityhall, dist_ugb,
    contains("con"), contains("pct")) %>%
  dplyr::select(-c("CONCRETE", "FIN SECOND", "PAVING/CONCRETE ONLY", "UNF SECOND", "conFldway", "pct_conFldway")) 
```

# Summary Statistics

```{r, echo = TRUE}

mu_sumdat <- mu_dat1 %>%
    # Select and rename
    dplyr::select(
        `Assessed Land Value (2017)` = LANDVAL3,
        `Assessed Market Value (2017)` = BLDGVAL3,
        `Total Assessed Value (2017)` = TOTALVAL3,
        
        `Sale Price` = SALEPRICE,
        `Log Sale Price` = SALEPRICElog,
        `Age When Sold` = age_sold,
        `Building Footprint (sqft)` = totalsqft,
        `Building Footprint Squared (sqft)` = totalsqft_sqd,
        `Taxlot Area (sqft)` = taxlot_area,
        `Taxlot Area Squared (sqft)` = taxlot_area_sqd,
        `Building Volume` = volume,
        
        `Floors` = FLOORS,
        `Units` = UNITS,
        `Full Baths` = f_baths,
        `Half Baths` = h_baths,
        `Fireplaces` = n_fireplaces,
        `Fireplaces Dummy` = fireplace_dum,
        `Accessible Dwelling Unit Dummy` = ADUdummy,
        `Garage Dummy` = garage_dum,
        `Garage Area (sqft)` = garage_sqft,
        `Basement Dummy` = bsmt_dum,
        `Basement Area (sqft)` = bsmt_sqft,
        
        `Vacant Properties in 200ft Radius (%)` = percent_vacant,
        `Vacant Properties in 200ft Radius Dummy` = vacant_dummy,
        `Canopy Cover (% of lot)` = pct_canopy_cov,
        `Canopy Cover (sqft)` = total_canopy_cov,
        `Canopy Cover Dummy` = canopy_dum,
        `Zoning Change Dummy` = zone_change,
        `Complete Neighborhoods Score (0-100)` = CN_score,
        `Distance to Central Business District (ft)` = dist_cityhall,
        `Distance to Urban Growth Boundary (ft)` = dist_ugb,
        #`Neighborhood Fixed Effects` = Neighborhood,
        #`High School Fixed Effects` = HIGH_SCH,
        #`Elementary School Fixed Effects` = ELEM_SCH,
        
        `DEQ Environmental Cleanup Sites (ECSI)` = conECSI,
        `DEQ Leaking Underground Storage Tank Cleanup Sites (LUST)` = conLUST,
        `Historic and Conservation Districts` = conHist,
        `Historic and Conservation Landmarks` = conECSI,
        `Areas Requiring Archeological Scan or Consultation with Tribes` = conNatAm,
        `Approach and Departure Cones` = conAirHgt,
        `Helipad Landing` = conHeliprt,
        `Airport Noise` = conNoise,
        `Greenway` = conGW,
        `DOGAMI Landslide Hazard Area` = conLSHA,
        `DOGAMI Digital Landslide Database (SLIDO)` = conSLIDO,
        `Slopes Over 25% Incline)` = conSlp25,
        `Institutional Campuses` = conInstit,
        `Private/Common Open Space` = conPrvCom,
        `Publicly Owned Lots (non-residential)` = conPubOwn,
        `Sewer System` = conSewer,
        `Stormwater System` = conStorm,
        `Water System` = conWater,
        `Traffic Volume Exceeds Capacity` = conTranCap,
        `ODOT Highway Interchanges` = conTranInt,
        `Substandard and Unimproved Streets` = conTranSub,
        `Scenic Views` = conView,
        `Conservation Zones` = conCovrly,
        `Preservation Zones` = conPovrly,
        `Wetlands` = conWetland,
        `FEMA 100-Year Floodplain Map` = conFld100,
        `Percent of Preservation Zones` = pct_conPovrly,
        `Percent of Conservation Zones` = pct_conCovrly,
        `Percent of Wetlands` = pct_conWetland,
        `Percent of FEMA 100_Year Floodplain Map` = pct_conFld100,
        )

mu_sumstat <- mu_sumdat %>%
    # Find the mean, st. dev., min, and max for each variable 
  summarise_all(funs(mean, sd, min, max), na.rm = TRUE) %>%
  pivot_longer(everything(),
               names_to = c("key", "variable"), 
               names_pattern = "(.*)_(.*)") %>%
  pivot_wider(everything(),
              names_from = variable,
              values_from = value)

# fix decimal places
mu_sumstat[,-1] <- round(mu_sumstat[,-1], 2)



# Write to .txt
write.table(mu_sumstat, file = "MUsumstats.txt", sep = ",", quote = FALSE, row.names = F)

```


# Regression 1: Pre-analysis Formula and Functional Forms (Dummies)


```{r, echo = TRUE}

# LINEAR REGRESSION-----------------------------------------

# dummies only
preanalysis_lin = formula(paste0("SALEPRICE ~ 
                         age_sold + totalsqft + totalsqft_sqd + taxlot_area + 
                         taxlot_area_sqd + volume + f_baths + h_baths + 
                         fireplace_dum + ADUdummy +  
                         garage_dum + bsmt_dum +
                         vacant_dummy + canopy_dum + zone_change +
                         CN_score + Neighborhood + HIGH_SCH + 
                         dist_cityhall + dist_ugb + ", con_names))
preanalysis_lin.mod <- lm(preanalysis_lin, mu_dat1)

# SEMI-LOG REGRESSION-------------------------------------------

preanalysis_log = formula(paste0("SALEPRICElog ~ 
                             age_sold + totalsqft + totalsqft_sqd + taxlot_area + 
                         taxlot_area_sqd + volume + f_baths + h_baths + 
                         fireplace_dum + ADUdummy +  
                         garage_dum + bsmt_dum +
                         vacant_dummy + canopy_dum + zone_change +
                         CN_score + Neighborhood + HIGH_SCH + 
                         dist_cityhall + dist_ugb + ", con_names))
preanalysis_log.mod <- lm(preanalysis_log, mu_dat1)

# BOX-COX (LINEAR) REGRESSION--------------------------------------------

bc = boxcox(preanalysis_lin.mod, lamba = seq(-3, 3, 1))
best_lam = bc$x[which(bc$y == max(bc$y))]
mu_dat1 %<>% 
  mutate(SALEPRICEbc = SALEPRICE^best_lam)

preanalysis_bc = formula(paste0("SALEPRICEbc ~ 
                                age_sold + totalsqft + totalsqft_sqd + taxlot_area + 
                         taxlot_area_sqd + volume + f_baths + h_baths + 
                         fireplace_dum + ADUdummy +  
                         garage_dum + bsmt_dum +
                         vacant_dummy + canopy_dum + zone_change +
                         CN_score + Neighborhood + HIGH_SCH + 
                         dist_cityhall + dist_ugb + ", con_names))
preanalysis_bc.mod <- lm(preanalysis_bc, mu_dat1)

```


# Regression 2: Dummy vs Square Feet Improvements

```{r}
# LINEAR REGRESSION DUMMY-----------------------------------------

# formula: only dummies
# preanalysis_lin = formula(paste0("SALEPRICE ~ 
#                          age_sold + totalsqft + totalsqft_sqd + taxlot_area + 
#                          taxlot_area_sqd + volume + f_baths + h_baths + 
#                          fireplace_dum + ADUdummy +  
#                          garage_dum + attic_dum + bsmt_dum + bsmt_dum +
#                          vacant_dummy + canopy_dum + zone_change +
#                          CN_score + Neighborhood + HIGH_SCH + 
#                          dist_cityhall + dist_ugb + ", con_names))
# preanalysis_lin.mod <- lm(preanalysis_lin, mu_dat1)


# LINEAR REGRESSION SQFT-----------------------------------------

sqft_log = formula(paste0("SALEPRICElog ~ 
                         age_sold + totalsqft + totalsqft_sqd + taxlot_area + 
                         taxlot_area_sqd + volume + f_baths + h_baths + 
                         n_fireplaces + ADUdummy +  
                         garage_sqft + deck_sqft +
                         vacant_dummy + total_canopy_cov + zone_change +
                         CN_score + Neighborhood + HIGH_SCH + 
                         dist_cityhall + dist_ugb + ", con_names))
sqft_log.mod <- lm(sqft_log, mu_dat1)
# n_fireplaces, improvement sqft, total canopy cov

```


# Regression 3: Dummy vs Percent Controls

```{r}
#  DUMMY REGRESSION--------------------------------------------
# formula: only dummies
# preanalysis_lin = formula(paste0("SALEPRICE ~ 
#                          age_sold + totalsqft + totalsqft_sqd + taxlot_area + 
#                          taxlot_area_sqd + volume + f_baths + h_baths + 
#                          fireplace_dum + ADUdummy +  
#                          garage_dum + attic_dum + bsmt_dum + bsmt_dum +
#                          vacant_dummy + canopy_dum + zone_change +
#                          CN_score + Neighborhood + HIGH_SCH + 
#                          dist_cityhall + dist_ugb + ", con_names))
# preanalysis_lin.mod <- lm(preanalysis_lin, mu_dat1)


#  PERCENT REGRESSION--------------------------------------------
# percent vacant but dummy imps
percent_log = formula(paste0("SALEPRICElog ~ 
                         age_sold + totalsqft + totalsqft_sqd + taxlot_area + 
                         taxlot_area_sqd + volume + f_baths + h_baths + 
                         fireplace_dum + ADUdummy +  
                         garage_dum + bsmt_dum +
                         percent_vacant + pct_canopy_cov + zone_change +
                         CN_score + Neighborhood + HIGH_SCH + 
                         dist_cityhall + dist_ugb + ", con_names))
percent_log.mod <- lm(percent_log, mu_dat1)
```


# Regression 4: Zoning History

```{r}
#  ZONING HISTORY --------------------------------------------

nozone_log = formula(paste0("SALEPRICElog ~ 
                         age_sold + totalsqft + totalsqft_sqd + taxlot_area + 
                         taxlot_area_sqd + volume + f_baths + h_baths + 
                         fireplace_dum + ADUdummy +  
                         garage_dum + bsmt_dum +
                         vacant_dummy + canopy_dum  +
                         CN_score + Neighborhood + HIGH_SCH + 
                         dist_cityhall + dist_ugb + ", con_names))
nozone_log.mod <- lm(nozone_log, mu_dat1)


# compare to preanalysis log

```


# Regression 5: Spatial Effects

```{r}
# PREANALYSIS LOG REGRESSION-----------------------------------------



# ONLY CN_SCORE, no neighborhood, highschool-----------------------------------------

cn_log = formula(paste0("SALEPRICElog ~ 
                             age_sold + totalsqft + totalsqft_sqd + taxlot_area + 
                         taxlot_area_sqd + volume + f_baths + h_baths + 
                         fireplace_dum + ADUdummy +  
                         garage_dum + bsmt_dum +
                         vacant_dummy + canopy_dum + zone_change +
                         CN_score + 
                         dist_cityhall + dist_ugb + ", con_names))
cn_log.mod <- lm(cn_log, mu_dat1)

# ONLY NEIGHBORHOOD FIXED EFFECTS, no cn_score, high school-----------------------------

neighborhood_log = formula(paste0("SALEPRICElog ~ 
                             age_sold + totalsqft + totalsqft_sqd + taxlot_area + 
                         taxlot_area_sqd + volume + f_baths + h_baths + 
                         fireplace_dum + ADUdummy +  
                         garage_dum + bsmt_dum +
                         vacant_dummy + canopy_dum + zone_change +
                         Neighborhood + 
                         dist_cityhall + dist_ugb + ", con_names))
neighborhood_log.mod <- lm(neighborhood_log, mu_dat1)

# ONLY HIGH SCHOOL, no neighborhood or cn_score-----------------------------------------

highsch_log = formula(paste0("SALEPRICElog ~ 
                             age_sold + totalsqft + totalsqft_sqd + taxlot_area + 
                         taxlot_area_sqd + volume + f_baths + h_baths + 
                         fireplace_dum + ADUdummy +  
                         garage_dum + bsmt_dum +
                         vacant_dummy + canopy_dum + zone_change +
                         HIGH_SCH + 
                         dist_cityhall + dist_ugb + ", con_names))
highsch_log.mod <- lm(highsch_log, mu_dat1)


# Replace high school with elementary school, keep all----------------------------------

elemsch_all_log = formula(paste0("SALEPRICElog ~ 
                             age_sold + totalsqft + totalsqft_sqd + taxlot_area + 
                         taxlot_area_sqd + volume + f_baths + h_baths + 
                         fireplace_dum + ADUdummy +  
                         garage_dum + bsmt_dum +
                         vacant_dummy + canopy_dum + zone_change +
                         CN_score + Neighborhood + ELEM_SCH + 
                         dist_cityhall + dist_ugb + ", con_names))
elemsch_all_log.mod <- lm(elemsch_all_log, mu_dat1)

# Replace high school with elementary school, remove cn_score and neighborhoods---------

elemsch_log = formula(paste0("SALEPRICElog ~ 
                             age_sold + totalsqft + totalsqft_sqd + taxlot_area + 
                         taxlot_area_sqd + volume + f_baths + h_baths + 
                         fireplace_dum + ADUdummy +  
                         garage_dum + bsmt_dum +
                         vacant_dummy + canopy_dum + zone_change +
                         ELEM_SCH + 
                         dist_cityhall + dist_ugb + ", con_names))
elemsch_log.mod <- lm(elemsch_log, mu_dat1)
```


### Regression 6: Mega Sexy Final Model

```{r}
#  MEGA SEXY MODEL REGRESSION--------------------------------------------
final_log = formula(paste0("SALEPRICElog ~ 
                             age_sold + totalsqft + taxlot_area + 
                         + volume + f_baths + h_baths + 
                         fireplace_dum + ADUdummy +  
                         garage_dum + bsmt_dum +
                         percent_vacant + pct_canopy_cov + zone_change +
                         CN_score + 
                         dist_cityhall + dist_ugb + ", con_names))
final_log.mod <- lm(final_log, mu_dat1)


```


# OUTPUT FILES IN HTML

```{r}
# Regression #1: Pre-analysis Formula and Functional Forms
stargazer(
  preanalysis_lin.mod, preanalysis_log.mod, preanalysis_bc.mod,
  title = "Regression #1: Pre-analysis Formula and Functional Forms (Dummy)",
  column.labels = c("Linear", "Semi-Log", "Box-Cox"),
  keep.stat = c("rsq", "adj.rsq"),
  notes.align = "l",
  type="html", 
  out="MU_models_base.htm"
  )

# Regression 2: Dummy vs Square Feet Improvements
stargazer(
  preanalysis_log.mod, sqft_log.mod, 
  title = "Regression 2: Dummy vs Square Feet Improvements",
  column.labels = c("Dummy", "SQFT"),
  keep.stat = c("rsq", "adj.rsq"),
  notes.align = "l",
  type="html", 
  out="MU_models_dummysqft.htm")

# Regression 3: Dummy vs Percent Controls
stargazer(
  preanalysis_log.mod, percent_log.mod, 
  title = "Regression 3: Dummy vs Percent Controls",
  column.labels = c("Dummy", "Percent"),
  keep.stat = c("rsq", "adj.rsq"),
  notes.align = "l",
  type="html", 
  out="MU_models_dummypct.htm")


# Regression 4: Zoning History
stargazer(
  preanalysis_log.mod, nozone_log.mod, 
  title = "Regression 4: LLCs",
  column.labels = c("Base with Zoning", "without Zoning"),
  keep.stat = c("rsq", "adj.rsq"),
  notes.align = "l",
  type="html", 
  out="MU_models_zoning.htm")

# Regression 5: Spatial Effects
stargazer(
  preanalysis_log.mod, cn_log.mod, neighborhood_log.mod, highsch_log.mod, elemsch_all_log.mod, elemsch_log.mod, 
  title = "Varying Spatial Effects",
  column.labels = c("Log Base", "Complete Neighborhoods Score", "Neighborhood FE", "High School", "Elementary School, all", "Elementary School"),
  keep.stat = c("rsq", "adj.rsq"),
  notes.align = "l",
  type = "html",
  out="MU_models_spatial.htm")


### Regression 6: Mega Sexy Final Model
stargazer(
  final_log.mod, 
  type = "html",
  title = "Single-Family Residential Results",
  style = "aer",
  out = "MU_models_final.htm",
  column.labels = c("Sale Price (log)"),
  covariate.labels = c(
    "Age When Sold", "Building Footprint (sqft)", "Taxlot Area (sqft)",
    "Building Volume (cuft)", "Full Baths", "Half Baths", "Fireplace Dummy",
    "Accessible Dwelling Unit Dummy", "Garage Dummy", "Attic Dummy",
    "Basement Dummy", "Deck Dummy", "Vacant Properties in 200ft Radius (%)",
    "Canopy Cover (% of lot)", "Zoning Change Dummy",
    "Complete Neighborhoods Score (0-100)",
    "Distance to Central Business District (ft)",
    "Distance to Urban Growth Boundary (ft)",
        "DEQ Environmental Cleanup Sites (ECSI)",
        "DEQ Leaking Underground Storage Tank Cleanup Sites (LUST)",
        "Historic and Conservation Districts",
        "Historic and Conservation Landmarks",
        "Areas Requiring Archeological Scan or Consultation with Tribes",
        "Approach and Departure Cones",
        "Helipad Landing",
        "Airport Noise",
        "Greenway",
        "DOGAMI Landslide Hazard Area",
        "DOGAMI Digital Landslide Database (SLIDO)",
        "Slopes Over 25% Incline",
        "Institutional Campuses",
        "Private/Common Open Space",
        "Publicly Owned Lots (non-residential)",
        "Sewer System",
        "Stormwater System",
        "Water System",
        "Traffic Volume Exceeds Capacity",
        "ODOT Highway Interchanges",
        "Substandard and Unimproved Streets",
        "Scenic Views",
        "Conservation Zones",
        "Preservation Zones",
        "Wetlands",
        "FEMA 100-Year Floodplain Map",
        "Percent of Preservation Zones",
        "Percent of Conservation Zones",
        "Percent of Wetlands",
        "Percent of FEMA 100-Year Floodplain Map"), # rename labels
  coef = , # change 0 values
  apply.coef = , #change 0 values
  initial.zero = TRUE,
  notes = "",
  notes.align = "l",
  single.row = TRUE,
  header = FALSE)

```