---
title: "SFR_final"
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Import Packages + Read in Data

```{r, include = TRUE}
library(tidyverse)
library(magrittr)
library(here)
library(data.table)
library(MASS)
library(knitr)
library(stargazer)
library(lubridate)
library(mapview)
library(sf)

# read in csv
thesis_data <- read_csv(here::here("DATA","thesis-data.csv"))
```

# Wrangling

```{r, echo = TRUE}
# Split Data
SFR <- thesis_data %>%
  filter(PRPCD_DESC == "RESIDENTIAL IMPROVED", prop_type == "Single-family")

#-------------------------------------------------------------------------

# Make a string of constraints and percent canopy names called "con_names"
clean <- SFR %>%
  dplyr::select(contains("con"), contains("pct")) %>%
  dplyr::select(-c("CONCRETE", "FIN SECOND", "PAVING/CONCRETE ONLY", "UNF SECOND", "conFldway", "pct_conFldway")) 
clean_names <- names(clean)
con_names <- paste(clean_names, collapse = " + ")

# switch the NAs in the constraints to 0s
to0 <- function(x){ifelse(is.na(x), 0, x)}

#-------------------------------------------------------------------------

# Format SFR Dataframe: 
# Select variables, mutate filtering parameters. No actual filtering done at this point, all SFR vars kept. 
test1 <- SFR %>%
  dplyr::select(-c(OWNER2, OWNER3, OWNERZIP, 
            MKTVALYR1, MKTVALYR2,
            BLDGVAL1, BLDGVAL2,
            LANDVAL1, LANDVAL2,  
            TOTALVAL1, TOTALVAL2,
            MS_GRADE, ES_GRADE,
            LEGAL_DESC, TAXCODE, 
            PROP_CODE, LANDUSE, 
            BEDROOMS, ACC_STATUS, 
            NAME, COMMPLAN, SHARED, 
            COALIT, HORZ_VERT, AUDIT_NBRH, 
            MIDDLE_SCH,  Category, SOURCE, 
            FRONTAGE, COUNTY, YEARBUILT, bldgtype)) %>%
  mutate(top_1 =  SALEPRICE > quantile(SALEPRICE, .99),
         MKTVALYR3 = case_when(MKTVALYR3 != 2018 ~ 2017, 
                                         TRUE ~ 2018),
         price_diff = SALEPRICE - LANDVAL3, 
         price_ratio = SALEPRICE/LANDVAL3 * 100,
         vacant_dummy = as.numeric(PRPCD_DESC == "VACANT LAND"),
         llc_flag = grepl("LLC", OWNER1),
         proud_flag =  grepl("PROUD", OWNER1),
         trust_flag = grepl("TRUST", OWNER1) & !grepl("FAMILY", OWNER1) & !grepl("LIVING", OWNER1)) 

#-------------------------------------------------------------------------

#garage sqft
gar_sqft_sum <- test1 %>%
  dplyr::select(matches("gar"), matches("car")) %>%
  rowSums()

#deck/patio/porch sqft
deck_sqft_sum <- test1 %>%
  dplyr::select(matches("deck"), matches("patio"), matches("porch")) %>%
  rowSums()

# attic sqft
attic_sqft_sum <- test1 %>%
  dplyr::select(matches("attic")) %>%
  rowSums()

# basement sqft
bsmt_sqft_sum <- test1 %>%
  dplyr::select(matches("bsmt")) %>%
  dplyr::select(-c("BSMT PARKING","BSMT GAR")) %>%
  rowSums()

# creating zone change dummy
zone_test <- test1 %>%
  dplyr::select(matches("zone"), -c(ZONE_DESC_aug2016, ZONE_DESC_aug2018, ZONE_DESC_feb2018, `Zone Description`, sale_zone)) %>%
  mutate_all(str_replace, pattern = "R", replacement = "") %>%
  mutate_all(funs(as.numeric)) %>%
  rowSums()


test1 %<>%
  mutate(garage_sqft = gar_sqft_sum,
         garage_dum = as.numeric(garage_sqft > 0),
         deck_sqft = deck_sqft_sum,
         deck_dum = as.numeric(deck_sqft > 0),
         attic_sqft = attic_sqft_sum,
         attic_dum = as.numeric(attic_sqft > 0),
         bsmt_sqft = bsmt_sqft_sum,
         bsmt_dum = as.numeric(bsmt_sqft > 0),
         n_fireplaces = replace_na(n_fireplaces, 0),
         fireplace_dum = as.numeric(n_fireplaces > 0),
         ADUdummy = as.numeric(ADUdummy > 0),
         total_canopy_cov = replace_na(total_canopy_cov, 0),
         canopy_dum = as.numeric(total_canopy_cov > 0),
         sum_z = zone_test,
         avg_z = sum_z/9,
         z_change = case_when(avg_z == 5 ~ 0,
                                      TRUE ~ 1),
         totalsqft_sqd = totalsqft*totalsqft,
         taxlot_area_sqd = taxlot_area*taxlot_area)

#-------------------------------------------------------------------------

# Clean SFR dataframe: 
# remove based on filtering parameters, set NAs as zero, add in improvements
test2 <- test1 %>%
  dplyr::select(-c(matches("zone"))) %>%
  mutate_at(vars(clean_names), to0) %>%
  mutate(arms_length = price_ratio > 20,
         yearbuilt = na_if(yearbuilt, 0),
         saledate = mdy(saledate), 
         year_sold = year(saledate),
         age_sold = year_sold - yearbuilt,
         percent_vacant = percent_vacant*100,
         SALEPRICElog = log(SALEPRICE)) %>%
  filter(between(totalsqft, 1, 7500), 
         yearbuilt > 1500,
         f_baths < 6,
         BLDGSQFT != 0,
         age_sold > 0, 
         top_1 == FALSE, 
         arms_length == TRUE, 
         vacant_dummy == FALSE, 
         proud_flag == FALSE, 
         llc_flag == FALSE,
         trust_flag == FALSE) 

#-------------------------------------------------------------------------

# Select final relevant variables
dat1 <- test2 %>%
  dplyr::select(
    STATE_ID, RNO, PROPERTYID, TLID, 
    OWNER1, SITEADDR, SITEZIP, PRPCD_DESC, 
    MKTVALYR3, LANDVAL3, BLDGVAL3, TOTALVAL3, 
    saledate, SALEPRICE, SALEPRICElog, age_sold,
    totalsqft, totalsqft_sqd, taxlot_area, taxlot_area_sqd, volume, 
    f_baths, h_baths, n_fireplaces, fireplace_dum, ADUdummy, 
    garage_sqft, garage_dum, deck_sqft, deck_dum, 
    attic_sqft, attic_dum, bsmt_sqft, bsmt_dum, 
    percent_vacant, vacant_dummy,
    pct_canopy_cov, total_canopy_cov, canopy_dum, zone_change = z_change,
    CN_score, Neighborhood = MapLabel, HIGH_SCH, ELEM_SCH, dist_cityhall, dist_ugb,
    contains("con"), contains("pct")) %>%
  dplyr::select(-c("CONCRETE", "FIN SECOND", "PAVING/CONCRETE ONLY", "UNF SECOND", "conFldway", "pct_conFldway")) 
```

# Summary Statistics

```{r, echo = TRUE}

sumdat <- dat1 %>%
    # Select and rename
    dplyr::select(
        `Assessed Land Value (2017)` = LANDVAL3,
        `Assessed Market Value (2017)` = BLDGVAL3,
        `Total Assessed Value (2017)` = TOTALVAL3,
        
        `Sale Price` = SALEPRICE,
        `Log Sale Price` = SALEPRICElog,
        `Age When Sold` = age_sold,
        `Building Footprint (sqft)` = totalsqft,
        `Building Footprint Squared (sqft)` = totalsqft_sqd,
        `Taxlot Area (sqft)` = taxlot_area,
        `Taxlot Area Squared (sqft)` = taxlot_area_sqd,
        `Building Volume` = volume,
        
        `Full Baths` = f_baths,
        `Half Baths` = h_baths,
        `Fireplaces` = n_fireplaces,
        `Fireplaces Dummy` = fireplace_dum,
        `Accessible Dwelling Unit Dummy` = ADUdummy,
        `Garage Dummy` = garage_dum,
        `Garage Area (sqft)` = garage_sqft,
        `Attic Dummy` = attic_dum,
        `Attic Area (sqft)` = attic_sqft,
        `Basement Dummy` = bsmt_dum,
        `Basement Area (sqft)` = bsmt_sqft,
        `Deck Dummy` = deck_dum,
        `Deck Area (sqft)` = deck_sqft,
        
        `Vacant Properties in 200ft Radius (%)` = percent_vacant,
        `Vacant Properties in 200ft Radius Dummy` = vacant_dummy,
        `Canopy Cover (% of lot)` = pct_canopy_cov,
        `Canopy Cover (sqft)` = total_canopy_cov,
        `Canopy Cover Dummy` = canopy_dum,
        `Zoning Change Dummy` = zone_change,
        `Complete Neighborhoods Score (0-100)` = CN_score,
        `Distance to Central Business District (ft)` = dist_cityhall,
        `Distance to Urban Growth Boundary (ft)` = dist_ugb,
        #`Neighborhood Fixed Effects` = Neighborhood,
        #`High School Fixed Effects` = HIGH_SCH,
        #`Elementary School Fixed Effects` = ELEM_SCH,
        
        `DEQ Environmental Cleanup Sites (ECSI)` = conECSI,
        `DEQ Leaking Underground Storage Tank Cleanup Sites (LUST)` = conLUST,
        `Historic and Conservation Districts` = conHist,
        `Historic and Conservation Landmarks` = conECSI,
        `Areas Requiring Archeological Scan or Consultation with Tribes` = conNatAm,
        `Approach and Departure Cones` = conAirHgt,
        `Helipad Landing` = conHeliprt,
        `Airport Noise` = conNoise,
        `Greenway` = conGW,
        `DOGAMI Landslide Hazard Area` = conLSHA,
        `DOGAMI Digital Landslide Database (SLIDO)` = conSLIDO,
        `Slopes Over 25% Incline)` = conSlp25,
        `Institutional Campuses` = conInstit,
        `Private/Common Open Space` = conPrvCom,
        `Publicly Owned Lots (non-residential)` = conPubOwn,
        `Sewer System` = conSewer,
        `Stormwater System` = conStorm,
        `Water System` = conWater,
        `Traffic Volume Exceeds Capacity` = conTranCap,
        `ODOT Highway Interchanges` = conTranInt,
        `Substandard and Unimproved Streets` = conTranSub,
        `Scenic Views` = conView,
        `Conservation Zones` = conCovrly,
        `Preservation Zones` = conPovrly,
        `Wetlands` = conWetland,
        `FEMA 100-Year Floodplain Map` = conFld100,
        `Percent of Preservation Zones` = pct_conPovrly,
        `Percent of Conservation Zones` = pct_conCovrly,
        `Percent of Wetlands` = pct_conWetland,
        `Percent of FEMA 100_Year Floodplain Map` = pct_conFld100,
        )

sumstat <- sumdat %>%
    # Find the mean, st. dev., min, and max for each variable 
  summarise_all(funs(mean, sd, min, max), na.rm = TRUE) %>%
  pivot_longer(everything(),
               names_to = c("key", "variable"), 
               names_pattern = "(.*)_(.*)") %>%
  pivot_wider(everything(),
              names_from = variable,
              values_from = value)

# fix decimal places
sumstat[,-1] <- round(sumstat[,-1], 2)



# Write to .txt
write.table(sumstat, file = "SFRsumstats.txt", sep = ",", quote = FALSE, row.names = F)

```


# Regression 1: Pre-analysis Formula and Functional Forms

```{r, echo = TRUE}

# LINEAR REGRESSION-----------------------------------------

# formula: only dummies, no percent except for percent canopy cover
sfr_lin = formula(paste0("SALEPRICE ~ 
                         CN_score + percent_vacant + dist_cityhall + dist_ugb + totalsqft + f_baths + h_baths + n_fireplaces + ADUdummy + pct_canopy_cov + taxlot_area + garage_dum + attic_dum + bsmt_dum + deck_dum + age_sold + MapLabel + HIGH_SCH + ", con_names))

sfr_lin_mod <- lm(sfr_lin, dat1)

# BOX-COX (LINEAR) REGRESSION--------------------------------------------

bc = boxcox(sfr_lin_mod, lamba = seq(-3, 3, 1))
best_lam = bc$x[which(bc$y == max(bc$y))]
dat1 %<>% 
  mutate(SALEPRICEbc = SALEPRICE^best_lam)

sfr_bc = formula(paste0("SALEPRICEbc ~ 
                             CN_score + percent_vacant + dist_cityhall + dist_ugb + totalsqft + f_baths + h_baths + n_fireplaces + ADUdummy + pct_canopy_cov + taxlot_area + garage_dum + attic_dum + bsmt_dum + deck_dum + age_sold + MapLabel + HIGH_SCH + ", con_names))

sfr_mod_bc <- lm(sfr_bc, dat1)

# SEMI-LOG REGRESSION-------------------------------------------

sfr_log = formula(paste0("SALEPRICElog ~ 
                             CN_score + percent_vacant + dist_cityhall + dist_ugb + totalsqft + f_baths + h_baths + n_fireplaces + ADUdummy + pct_canopy_cov + taxlot_area + garage_dum + attic_dum + bsmt_dum + deck_dum + age_sold + MapLabel + HIGH_SCH + ", con_names))

sfr_mod_log <- lm(sfr_log, dat1)
```


