---
title: "SFR_final"
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Import Packages + Read in Data

```{r, include = TRUE}
library(tidyverse)
library(magrittr)
library(here)
library(data.table)
library(MASS)
library(knitr)
library(stargazer)
library(lubridate)
library(mapview)
library(sf)

# read in csv
thesis_data <- read_csv(here::here("DATA","thesis-data.csv"))
```

# Wrangling

```{r, echo = TRUE}
# Split Data
SFR <- thesis_data %>%
  filter(PRPCD_DESC == "RESIDENTIAL IMPROVED", prop_type == "Single-family")

#-------------------------------------------------------------------------

# Make a string of constraints and percent canopy names called "con_names"
clean <- SFR %>%
  dplyr::select(conECSI, conLUST, 
                conHist, conHistLdm, conNatAm,
                conCovrly, conPovrly,
                conAirHgt, conHeliprt, conNoise,
                conGW,
                conLSHA, conSLIDO, conFld100, conSlp25, 
                conSewer, conStorm, conWater,
                conWetland,
                conInstit, conPrvCom, conPubOwn,
                conView,
                conTranCap, conTranInt, conTranSub)
clean_names <- names(clean)
con_names <- paste(clean_names, collapse = " + ")

# switch the NAs in the constraints to 0s
to0 <- function(x){ifelse(is.na(x), 0, x)}

#-------------------------------------------------------------------------

# Format SFR Dataframe: 
# Select variables, mutate filtering parameters. No actual filtering done at this point, all SFR vars kept. 
test1 <- SFR %>%
  dplyr::select(-c(OWNER2, OWNER3, OWNERZIP, 
            MKTVALYR1, MKTVALYR2,
            BLDGVAL1, BLDGVAL2,
            LANDVAL1, LANDVAL2,  
            TOTALVAL1, TOTALVAL2,
            MS_GRADE, ES_GRADE,
            LEGAL_DESC, TAXCODE, 
            PROP_CODE, LANDUSE, 
            BEDROOMS, ACC_STATUS, 
            NAME, COMMPLAN, SHARED, 
            COALIT, HORZ_VERT, AUDIT_NBRH, 
            MIDDLE_SCH,  Category, SOURCE, 
            FRONTAGE, COUNTY, YEARBUILT, bldgtype)) %>%
  mutate(top_1 =  SALEPRICE > quantile(SALEPRICE, .99),
         MKTVALYR3 = case_when(MKTVALYR3 != 2018 ~ 2017, 
                                         TRUE ~ 2018),
         price_diff = SALEPRICE - LANDVAL3, 
         price_ratio = SALEPRICE/LANDVAL3 * 100,
         vacant_dummy = as.numeric(PRPCD_DESC == "VACANT LAND"),
         llc_flag = grepl("LLC", OWNER1),
         proud_flag =  grepl("PROUD", OWNER1),
         trust_flag = grepl("TRUST", OWNER1) & !grepl("FAMILY", OWNER1) & !grepl("LIVING", OWNER1)) 

#-------------------------------------------------------------------------

#garage sqft
gar_sqft_sum <- test1 %>%
  dplyr::select(matches("gar"), matches("car")) %>%
  rowSums()

#deck/patio/porch sqft
deck_sqft_sum <- test1 %>%
  dplyr::select(matches("deck"), matches("patio"), matches("porch")) %>%
  rowSums()

# attic sqft
attic_sqft_sum <- test1 %>%
  dplyr::select(matches("attic")) %>%
  rowSums()

# basement sqft
bsmt_sqft_sum <- test1 %>%
  dplyr::select(matches("bsmt")) %>%
  dplyr::select(-c("BSMT PARKING","BSMT GAR")) %>%
  rowSums()

# creating zone change dummy
zone_test <- test1 %>%
  dplyr::select(matches("zone"), -c(ZONE_DESC_aug2016, ZONE_DESC_aug2018, ZONE_DESC_feb2018, `Zone Description`, sale_zone)) %>%
  mutate_all(str_replace, pattern = "R", replacement = "") %>%
  mutate_all(funs(as.numeric)) %>%
  rowSums()


test1 %<>%
  mutate(garage_sqft = gar_sqft_sum,
         garage_dum = as.numeric(garage_sqft > 0),
         deck_sqft = deck_sqft_sum,
         deck_dum = as.numeric(deck_sqft > 0),
         attic_sqft = attic_sqft_sum,
         attic_dum = as.numeric(attic_sqft > 0),
         bsmt_sqft = bsmt_sqft_sum,
         bsmt_dum = as.numeric(bsmt_sqft > 0),
         n_fireplaces = replace_na(n_fireplaces, 0),
         fireplace_dum = as.numeric(n_fireplaces > 0),
         ADUdummy = as.numeric(ADUdummy > 0),
         total_canopy_cov = replace_na(total_canopy_cov, 0),
         canopy_dum = as.numeric(total_canopy_cov > 0),
         sum_z = zone_test,
         avg_z = sum_z/9,
         z_change = case_when(avg_z == 5 ~ 0,
                                      TRUE ~ 1),
         totalsqft_sqd = totalsqft*totalsqft,
         taxlot_area_sqd = taxlot_area*taxlot_area)

#-------------------------------------------------------------------------

# Clean SFR dataframe: 
# remove based on filtering parameters, set NAs as zero, add in improvements
test2 <- test1 %>%
  dplyr::select(-c(matches("zone"))) %>%
  mutate_at(vars(clean_names), to0) %>%
  mutate(arms_length = price_ratio > 20,
         yearbuilt = na_if(yearbuilt, 0),
         saledate = mdy(saledate), 
         year_sold = year(saledate),
         age_sold = year_sold - yearbuilt,
         pct_canopy_cov = pct_canopy_cov*100,
         SALEPRICElog = log(SALEPRICE)) %>%
  filter(between(totalsqft, 1, 7500), 
         yearbuilt > 1500,
         f_baths < 6,
         BLDGSQFT != 0,
         age_sold > 0, 
         top_1 == FALSE, 
         arms_length == TRUE, 
         vacant_dummy == FALSE, 
         proud_flag == FALSE, 
         llc_flag == FALSE,
         trust_flag == FALSE) 


mary <- dat1 %>% 
  filter(percent_vacant > 99) 
         proud_flag == FALSE, 
         llc_flag == FALSE,
         trust_flag == FALSE)
brady <- 25266 - nrow(dat1)
brady
brady/25266

mean(mary$SALEPRICE)
median(mary$SALEPRICE)
#-------------------------------------------------------------------------

# Select final relevant variables
dat1 <- test2 %>%
  dplyr::select(
    STATE_ID, RNO, PROPERTYID, TLID, 
    OWNER1, SITEADDR, SITEZIP, PRPCD_DESC, 
    MKTVALYR3, LANDVAL3, BLDGVAL3, TOTALVAL3, 
    saledate, SALEPRICE, SALEPRICElog, age_sold,
    totalsqft, totalsqft_sqd, taxlot_area, taxlot_area_sqd, volume, 
    f_baths, h_baths, n_fireplaces, fireplace_dum, ADUdummy, 
    garage_sqft, garage_dum, deck_sqft, deck_dum, 
    attic_sqft, attic_dum, bsmt_sqft, bsmt_dum, 
    percent_vacant, vacant_dummy,
    pct_canopy_cov, total_canopy_cov, canopy_dum, zone_change = z_change,
    CN_score, Neighborhood = MapLabel, HIGH_SCH, ELEM_SCH, dist_cityhall, dist_ugb,
    contains("con"), contains("pct")) %>%
  dplyr::select(-c("CONCRETE", "FIN SECOND", "PAVING/CONCRETE ONLY", "UNF SECOND", "conFldway", "pct_conFldway")) 
```

# Summary Statistics

```{r, echo = TRUE}

sumdat_controls <- dat1 %>%
    # Select and rename
    dplyr::select(
        `Assessed Land Value (2017)` = LANDVAL3,
        `Assessed Market Value (2017)` = BLDGVAL3,
        `Total Assessed Value (2017)` = TOTALVAL3,
        
        `Sale Price` = SALEPRICE,
        `Log Sale Price` = SALEPRICElog,
        `Age When Sold` = age_sold,
        `Building Footprint (sqft)` = totalsqft,
        `Building Footprint Squared (sqft)` = totalsqft_sqd,
        `Taxlot Area (sqft)` = taxlot_area,
        `Taxlot Area Squared (sqft)` = taxlot_area_sqd,
        `Building Volume` = volume,
        
        `Full Baths` = f_baths,
        `Half Baths` = h_baths,
        `Fireplaces` = n_fireplaces,
        `Fireplaces Dummy` = fireplace_dum,
        `Accessible Dwelling Unit Dummy` = ADUdummy,
        `Garage Dummy` = garage_dum,
        `Garage Area (sqft)` = garage_sqft,
        `Attic Dummy` = attic_dum,
        `Attic Area (sqft)` = attic_sqft,
        `Basement Dummy` = bsmt_dum,
        `Basement Area (sqft)` = bsmt_sqft,
        `Deck Dummy` = deck_dum,
        `Deck Area (sqft)` = deck_sqft,
        
        `Vacant Properties in 200ft Radius (%)` = percent_vacant,
        `Canopy Cover (% of lot)` = pct_canopy_cov,
        `Canopy Cover (sqft)` = total_canopy_cov,
        `Canopy Cover Dummy` = canopy_dum,
        `Zoning Change Dummy` = zone_change,
        `Complete Neighborhoods Score (0-100)` = CN_score,
        `Distance to Central Business District (ft)` = dist_cityhall,
        `Distance to Urban Growth Boundary (ft)` = dist_ugb,
        `Neighborhood Fixed Effects` = Neighborhood)
        #`High School Fixed Effects` = HIGH_SCH,
        #`Elementary School Fixed Effects` = ELEM_SCH,

sumdat_constraints <- dat1 %>%
    # Select and rename
    dplyr::select(
        `DEQ Environmental Cleanup Sites (ECSI)` = conECSI,
        `DEQ Leaking Underground Storage Tank Cleanup Sites (LUST)` = conLUST,
        
        `Historic and Conservation Districts` = conHist,
        `Historic and Conservation Landmarks` = conHistLdm,
        `Areas Requiring Archeological Scan or Consultation with Tribes` = conNatAm,
        
        `Percent of Preservation Zones` = pct_conPovrly,
        `Percent of Conservation Zones` = pct_conCovrly,
        
        `Approach and Departure Cones` = conAirHgt,
        `Helipad Landing` = conHeliprt,
        `Airport Noise` = conNoise,
        
        `Greenway` = conGW,
        
        `DOGAMI Landslide Hazard Area` = conLSHA,
        `DOGAMI Digital Landslide Database (SLIDO)` = conSLIDO,
        `FEMA 100-Year Floodplain Map` = conFld100,
        `Slopes Over 25% Incline` = conSlp25,
        
        `Sewer System` = conSewer,
        `Stormwater System` = conStorm,
        `Water System` = conWater,
        
        `Wetlands` = conWetland,
        
        `Institutional Campuses` = conInstit,
        `Private/Common Open Space` = conPrvCom,
        `Publicly Owned Lots` = conPubOwn,

        `Scenic Views` = conView,
        
        `Traffic Volume Exceeds Capacity` = conTranCap,
        `ODOT Highway Interchanges` = conTranInt,
        `Substandard and Unimproved Streets` = conTranSub
        )

# sumstat <- sumdat %>%
#     # Find the mean, st. dev., min, and max for each variable 
#   summarise_all(funs(mean, sd, min, max), na.rm = TRUE) %>%
#   pivot_longer(everything(),
#                names_to = c("key", "variable"), 
#                names_pattern = "(.*)_(.*)") %>%
#   pivot_wider(everything(),
#               names_from = variable,
#               values_from = value)
# 
# # fix decimal places
# sumstat[,-1] <- round(sumstat[,-1], 2)
# 
# 
# 
# # Write to .txt
# write.table(sumstat, file = "SFRsumstats.txt", sep = ",", quote = FALSE, row.names = F)

```


# Regression 1: Pre-analysis Formula and Functional Forms (Dummies)


```{r, echo = TRUE}

# LINEAR REGRESSION-----------------------------------------

# dummies only
preanalysis_lin = formula(paste0("SALEPRICE ~ 
                         age_sold + totalsqft + totalsqft_sqd + taxlot_area + 
                         taxlot_area_sqd + volume + f_baths + h_baths + 
                         fireplace_dum + ADUdummy +  
                         garage_dum + attic_dum + bsmt_dum + deck_dum +
                        canopy_dum + zone_change +
                         CN_score + Neighborhood + HIGH_SCH + 
                         dist_cityhall + dist_ugb + ", con_names))
preanalysis_lin.mod <- lm(preanalysis_lin, dat1)

# SEMI-LOG REGRESSION-------------------------------------------

preanalysis_log = formula(paste0("SALEPRICElog ~ 
                             age_sold + totalsqft + totalsqft_sqd + taxlot_area + 
                         taxlot_area_sqd + volume + f_baths + h_baths + 
                         fireplace_dum + ADUdummy +  
                         garage_dum + attic_dum + bsmt_dum + deck_dum +
                         canopy_dum + zone_change +
                         CN_score + Neighborhood + HIGH_SCH + 
                         dist_cityhall + dist_ugb + ", con_names))
preanalysis_log.mod <- lm(preanalysis_log, dat1)

# BOX-COX (LINEAR) REGRESSION--------------------------------------------

bc = boxcox(preanalysis_lin.mod, lamba = seq(-3, 3, 1))
best_lam = bc$x[which(bc$y == max(bc$y))]
dat1 %<>% 
  mutate(SALEPRICEbc = SALEPRICE^best_lam)

preanalysis_bc = formula(paste0("SALEPRICEbc ~ 
                                age_sold + totalsqft + totalsqft_sqd + taxlot_area + 
                         taxlot_area_sqd + volume + f_baths + h_baths + 
                         fireplace_dum + ADUdummy +  
                         garage_dum + attic_dum + bsmt_dum + deck_dum +
                          canopy_dum + zone_change +
                         CN_score + Neighborhood + HIGH_SCH + 
                         dist_cityhall + dist_ugb + ", con_names))
preanalysis_bc.mod <- lm(preanalysis_bc, dat1)

```


# Regression 2: Dummy vs Square Feet Improvements

```{r}
# LINEAR REGRESSION DUMMY-----------------------------------------

# formula: only dummies
# preanalysis_lin = formula(paste0("SALEPRICE ~ 
#                          age_sold + totalsqft + totalsqft_sqd + taxlot_area + 
#                          taxlot_area_sqd + volume + f_baths + h_baths + 
#                          fireplace_dum + ADUdummy +  
#                          garage_dum + attic_dum + bsmt_dum + deck_dum +
#                           canopy_dum + zone_change +
#                          CN_score + Neighborhood + HIGH_SCH + 
#                          dist_cityhall + dist_ugb + ", con_names))
# preanalysis_lin.mod <- lm(preanalysis_lin, dat1)


# LINEAR REGRESSION SQFT-----------------------------------------

sqft_log = formula(paste0("SALEPRICElog ~ 
                         age_sold + totalsqft + totalsqft_sqd + taxlot_area + 
                         taxlot_area_sqd + volume + f_baths + h_baths + 
                         n_fireplaces + ADUdummy +  
                         garage_sqft + attic_sqft + bsmt_sqft + deck_sqft +
                          total_canopy_cov + zone_change +
                         CN_score + Neighborhood + HIGH_SCH + 
                         dist_cityhall + dist_ugb + ", con_names))
sqft_log.mod <- lm(sqft_log, dat1)
# n_fireplaces, improvement sqft, total canopy cov

```


# Regression 3: Dummy vs Percent Controls

```{r}
#  DUMMY REGRESSION--------------------------------------------
# formula: only dummies
# preanalysis_lin = formula(paste0("SALEPRICE ~ 
#                          age_sold + totalsqft + totalsqft_sqd + taxlot_area + 
#                          taxlot_area_sqd + volume + f_baths + h_baths + 
#                          fireplace_dum + ADUdummy +  
#                          garage_dum + attic_dum + bsmt_dum + deck_dum +
#                           canopy_dum + zone_change +
#                          CN_score + Neighborhood + HIGH_SCH + 
#                          dist_cityhall + dist_ugb + ", con_names))
# preanalysis_lin.mod <- lm(preanalysis_lin, dat1)


#  PERCENT REGRESSION--------------------------------------------
# percent vacant but dummy imps
percent_log = formula(paste0("SALEPRICElog ~ 
                         age_sold + totalsqft + totalsqft_sqd + taxlot_area + 
                         taxlot_area_sqd + volume + f_baths + h_baths + 
                         fireplace_dum + ADUdummy +  
                         garage_dum + attic_dum + bsmt_dum + deck_dum +
                         percent_vacant + pct_canopy_cov + zone_change +
                         CN_score + Neighborhood + HIGH_SCH + 
                         dist_cityhall + dist_ugb + ", con_names))
percent_log.mod <- lm(percent_log, dat1)
```


# Regression 4: LLCs

```{r}
# ADD IN LLCS--------------------------------------------------------------

dat_llc <- test1 %>%
  dplyr::select(-c(matches("zone"))) %>%
  mutate_at(vars(clean_names), to0) %>%
  mutate(arms_length = price_ratio > 20,
         yearbuilt = na_if(yearbuilt, 0),
         saledate = mdy(saledate), 
         year_sold = year(saledate),
         age_sold = year_sold - yearbuilt,
         percent_vacant = percent_vacant*100,
         SALEPRICElog = log(SALEPRICE)) %>%
  filter(between(totalsqft, 1, 7500), 
         yearbuilt > 1500,
         f_baths < 6,
         BLDGSQFT != 0,
         age_sold > 0, 
         top_1 == FALSE, 
         arms_length == TRUE, 
         vacant_dummy == FALSE, 
         proud_flag == FALSE, 
         llc_flag == TRUE,
         trust_flag == FALSE) 

dat_llc %<>%
  dplyr::select(
    STATE_ID, RNO, PROPERTYID, TLID, 
    OWNER1, SITEADDR, SITEZIP, PRPCD_DESC, 
    MKTVALYR3, LANDVAL3, BLDGVAL3, TOTALVAL3, 
    saledate, SALEPRICE, SALEPRICElog, age_sold,
    totalsqft, totalsqft_sqd, taxlot_area, taxlot_area_sqd, volume, 
    f_baths, h_baths, n_fireplaces, fireplace_dum, ADUdummy, 
    garage_sqft, garage_dum, deck_sqft, deck_dum, 
    attic_sqft, attic_dum, bsmt_sqft, bsmt_dum, 
    percent_vacant, vacant_dummy,
    pct_canopy_cov, total_canopy_cov, canopy_dum, zone_change = z_change,
    CN_score, Neighborhood = MapLabel, HIGH_SCH, ELEM_SCH, dist_cityhall, dist_ugb,
    contains("con"), contains("pct")) %>%
  dplyr::select(-c("CONCRETE", "FIN SECOND", "PAVING/CONCRETE ONLY", "UNF SECOND", "conFldway", "pct_conFldway")) 


# dummies only------
preanalysis_llc_log = formula(paste0("SALEPRICElog ~ 
                         age_sold + totalsqft + totalsqft_sqd + taxlot_area + 
                         taxlot_area_sqd + volume + f_baths + h_baths + 
                         fireplace_dum + ADUdummy +  
                         garage_dum + attic_dum + bsmt_dum + deck_dum +
                          canopy_dum + zone_change +
                         CN_score + Neighborhood + HIGH_SCH + 
                         dist_cityhall + dist_ugb + ", con_names))

preanalysis_llc_log.mod <- lm(preanalysis_llc_log, dat_llc)

```


# Regression 5: Zoning History

```{r}
#  ZONING HISTORY --------------------------------------------

nozone_log = formula(paste0("SALEPRICElog ~ 
                         age_sold + totalsqft + totalsqft_sqd + taxlot_area + 
                         taxlot_area_sqd + volume + f_baths + h_baths + 
                         fireplace_dum + ADUdummy +  
                         garage_dum + attic_dum + bsmt_dum + deck_dum +
                          canopy_dum  +
                         CN_score + Neighborhood + HIGH_SCH + 
                         dist_cityhall + dist_ugb + ", con_names))
nozone_log.mod <- lm(nozone_log, dat1)


# compare to preanalysis log

```


# Regression 6: Spatial Effects

```{r}
# PREANALYSIS LOG REGRESSION-----------------------------------------



# ONLY CN_SCORE, no neighborhood, highschool-----------------------------------------

cn_log = formula(paste0("SALEPRICElog ~ 
                             age_sold + totalsqft + totalsqft_sqd + taxlot_area + 
                         taxlot_area_sqd + volume + f_baths + h_baths + 
                         fireplace_dum + ADUdummy +  
                         garage_dum + attic_dum + bsmt_dum + deck_dum +
                          canopy_dum + zone_change +
                         CN_score + 
                         dist_cityhall + dist_ugb + ", con_names))
cn_log.mod <- lm(cn_log, dat1)

# ONLY NEIGHBORHOOD FIXED EFFECTS, no cn_score, high school-----------------------------

neighborhood_log = formula(paste0("SALEPRICElog ~ 
                             age_sold + totalsqft + totalsqft_sqd + taxlot_area + 
                         taxlot_area_sqd + volume + f_baths + h_baths + 
                         fireplace_dum + ADUdummy +  
                         garage_dum + attic_dum + bsmt_dum + deck_dum +
                          canopy_dum + zone_change +
                         Neighborhood + 
                         dist_cityhall + dist_ugb + ", con_names))
neighborhood_log.mod <- lm(neighborhood_log, dat1)

# ONLY HIGH SCHOOL, no neighborhood or cn_score-----------------------------------------

highsch_log = formula(paste0("SALEPRICElog ~ 
                             age_sold + totalsqft + totalsqft_sqd + taxlot_area + 
                         taxlot_area_sqd + volume + f_baths + h_baths + 
                         fireplace_dum + ADUdummy +  
                         garage_dum + attic_dum + bsmt_dum + deck_dum +
                          canopy_dum + zone_change +
                         HIGH_SCH + 
                         dist_cityhall + dist_ugb + ", con_names))
highsch_log.mod <- lm(highsch_log, dat1)


# Replace high school with elementary school, keep all----------------------------------

elemsch_all_log = formula(paste0("SALEPRICElog ~ 
                             age_sold + totalsqft + totalsqft_sqd + taxlot_area + 
                         taxlot_area_sqd + volume + f_baths + h_baths + 
                         fireplace_dum + ADUdummy +  
                         garage_dum + attic_dum + bsmt_dum + deck_dum +
                          canopy_dum + zone_change +
                         CN_score + Neighborhood + ELEM_SCH + 
                         dist_cityhall + dist_ugb + ", con_names))
elemsch_all_log.mod <- lm(elemsch_all_log, dat1)

# Replace high school with elementary school, remove cn_score and neighborhoods---------

elemsch_log = formula(paste0("SALEPRICElog ~ 
                             age_sold + totalsqft + totalsqft_sqd + taxlot_area + 
                         taxlot_area_sqd + volume + f_baths + h_baths + 
                         fireplace_dum + ADUdummy +  
                         garage_dum + attic_dum + bsmt_dum + deck_dum +
                          canopy_dum + zone_change +
                         ELEM_SCH + 
                         dist_cityhall + dist_ugb + ", con_names))
elemsch_log.mod <- lm(elemsch_log, dat1)
```


### Regression 7: Mega Sexy Final Model

```{r}
#  MEGA SEXY MODEL REGRESSION--------------------------------------------
final_log = formula(paste0("SALEPRICElog ~ 
                             age_sold + totalsqft + taxlot_area + 
                         + volume + f_baths + h_baths + 
                         fireplace_dum + ADUdummy +  
                         garage_dum + attic_dum + bsmt_dum + deck_dum +
                         percent_vacant + pct_canopy_cov + zone_change +
                         CN_score + 
                         dist_cityhall + dist_ugb + ", con_names))
final_log.mod <- lm(final_log, dat1)

final_log.coef <- data.frame(coef = final_log.mod[["coefficients"]]) %>%
  filter(is.na(coef) == FALSE) %>%
  mutate(interpretlog = exp(coef) - 1)
                             
interpretlog <- as.vector(final_log.coef$interpretlog)

stargazer(
  as.data.frame(sumdat_controls),
  summary = TRUE,
  summary.stat = c("mean", "sd", "min", "max"),
  summary.logical = TRUE,
  digits = 2,
  type = "html",
  style = "io",
  title = "Single-family Residential Summary Statistics: Controls",
  out = "sumstats_controls_sfr.htm")

stargazer(
  as.data.frame(sumdat_constraints),
  summary = TRUE,
  summary.stat = c("mean", "sd", "min", "max"),
  summary.logical = TRUE,
  digits = 2,
  type = "html",
  style = "io",
  title = "Single-family Residential Summary Statistics: Development Constraints",
  out = "sumstats_constraints_sfr.htm")

eric <- summary(sumdat_constraints)
```


# OUTPUT FILES IN HTML

```{r}
# Regression #1: Pre-analysis Formula and Functional Forms
stargazer(
  preanalysis_lin.mod, preanalysis_log.mod, preanalysis_bc.mod,
  title = "Regression #1: Pre-analysis Formula and Functional Forms (Dummy)",
  column.labels = c("Linear", "Semi-Log", "Box-Cox"),
  keep.stat = c("rsq", "adj.rsq"),
  notes.align = "l",
  type="html", 
  out="models_base.htm"
  )

# Regression 2: Dummy vs Square Feet Improvements
stargazer(
  preanalysis_log.mod, sqft_log.mod, 
  title = "Regression 2: Dummy vs Square Feet Improvements",
  column.labels = c("Dummy", "SQFT"),
  keep.stat = c("rsq", "adj.rsq"),
  notes.align = "l",
  type="html", 
  out="models_dummysqft.htm")

# Regression 3: Dummy vs Percent Controls
stargazer(
  preanalysis_log.mod, percent_log.mod, 
  title = "Regression 3: Dummy vs Percent Controls",
  column.labels = c("Dummy", "Percent"),
  keep.stat = c("rsq", "adj.rsq"),
  notes.align = "l",
  type="html", 
  out="models_dummypct.htm")


# Regression 4: LLCs
stargazer(
  preanalysis_log.mod, preanalysis_llc_log.mod, 
  title = "Regression 4: LLCs",
  column.labels = c("Base without LLC", "with LLC"),
  keep.stat = c("rsq", "adj.rsq"),
  notes.align = "l",
  type="html", 
  out="models_llc.htm")

# Regression 5: Zoning History
stargazer(
  preanalysis_log.mod, nozone_log.mod, 
  title = "Regression 4: LLCs",
  column.labels = c("Base with Zoning", "without Zoning"),
  keep.stat = c("rsq", "adj.rsq"),
  notes.align = "l",
  type="html", 
  out="models_zoning.htm")

# Regression 6: Spatial Effects
stargazer(
  preanalysis_log.mod, cn_log.mod, neighborhood_log.mod, highsch_log.mod, elemsch_all_log.mod, elemsch_log.mod, 
  title = "Varying Spatial Effects",
  column.labels = c("Log Base", "Complete Neighborhoods Score", "Neighborhood FE", "High School", "Elementary School, all", "Elementary School"),
  keep.stat = c("rsq", "adj.rsq"),
  notes.align = "l",
  type = "html",
  out="models_spatial.htm")


### Regression 7: Mega Sexy Final Model
stargazer(
  final_log.mod,
  type = "html",
  title = "Single-Family Residential Results",
  style = "io",
  out = "models_finals.htm",
  column.labels = c("Log Sale Price <br> (standard error)", "Marginal Price (%)"),
  covariate.labels = c(
    "Constant",
    "Age When Sold", "Building Footprint (sqft)", "Taxlot Area (sqft)",
    "Building Volume (cuft)", "Full Baths", "Half Baths", "Fireplace Dummy",
    "Accessible Dwelling Unit Dummy", "Garage Dummy", "Attic Dummy",
    "Basement Dummy", "Deck Dummy", "Vacant Properties in 200ft Radius (%)",
    "Canopy Cover (% of lot)", "Zoning Change Dummy",
    "Complete Neighborhoods Score (0-100)",
    "Distance to Central Business District (ft)",
    "Distance to Urban Growth Boundary (ft)",
    
        "DEQ Environmental Cleanup Sites (ECSI)",
        "DEQ Leaking Underground Storage Tank Cleanup Sites (LUST)",
        "Historic and Conservation Districts",
        "Historic and Conservation Landmarks",
        "Areas Requiring Archeological Scan or Consultation with Tribes",
        "Conservation Zones",
        "Preservation Zones",
        "Approach and Departure Cones",
        "Helipad Landing",
        "Airport Noise",
        "Greenway",
        "DOGAMI Landslide Hazard Area",
        "DOGAMI Digital Landslide Database (SLIDO)",
        "FEMA 100-Year Floodplain Map",
        "Slopes Over 25% Incline",
        "Sewer System",
        "Stormwater System",
        "Water System",
        "Wetlands",
        "Institutional Campuses",
        "Private/Common Open Space",
        "Publicly Owned Lots",
        "Scenic Views",
        "Traffic Volume Exceeds Capacity",
        "ODOT Highway Interchanges",
        "Substandard and Unimproved Streets"), # rename labels
  initial.zero = TRUE,
  notes.align = "l",
  single.row = FALSE,
  keep.stat = c("n", "rsq"),
  no.space = TRUE,
  colnames = FALSE,
  digits.extra = 3,
  intercept.bottom = FALSE,
  header = FALSE)

summary(final_log.mod)


dat1 %>%
  filter(conGW == 1)

clean_vif <- SFR %>%
  dplyr::select(conECSI, conLUST, 
                conHist, conHistLdm,
                conCovrly, conPovrly,
                conAirHgt, conNoise,
                conGW,
                conLSHA, conSLIDO, conFld100, conSlp25, 
                conSewer, conStorm, conWater,
                conWetland,
                conPubOwn,
                conTranCap, conTranInt, conTranSub)
clean_vif_names <- names(clean_vif)
con_names_vif <- paste(clean_vif_names, collapse = " + ")

final_log_vif = formula(paste0("SALEPRICElog ~ 
                             age_sold + totalsqft + taxlot_area + 
                         + volume + f_baths + h_baths + 
                         fireplace_dum + ADUdummy +  
                         garage_dum + attic_dum + bsmt_dum + deck_dum +
                         percent_vacant + pct_canopy_cov + zone_change +
                         CN_score + 
                         dist_cityhall + dist_ugb + ", con_names_vif))

final_log_vif.mod <- lm(final_log_vif, dat1)


summary( final_log_vif.mod )
car::vif(final_log_vif.mod, singular.ok = T) 
car::vif(final_log.mod)

```